version: '3'

services:
  postgres:
    container_name: postgres-test
    image: postgres:12.5-alpine
    environment:
      POSTGRES_DB: payment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
